default: &default
  pool: 5
  timeout: 5000
  username: postgres
  password: 310888

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: mlb_data
  host: localhost

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: mlb_data
  host: localhost

staging:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: mlb_data
  prepared_statements: false

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: mlb_data
  prepared_statements: false
