# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54ae406f5ae483daad3a183edf92c3b90099611be659862df545d9ee567e9f498f37530c52ef3fa47edabe621da80aff76746d01c3f8b5641a0ec1c9bc6c875b

test:
  secret_key_base: 79ccc3b28e7be89b2e983f820caa4884e04a3d265ffc1e12d5cb85499b3f3d12207b333367b6524017bdf5e4fcf3517f1bef6174f72fd38de6ebdc75afd634d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
